#!/usr/bin/env node
// Generates src/version.ts from package.json.
// With --check: exits non-zero if the file is out of sync.
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const version = pkg.version;

const content =
	`// Generated by scripts/gen-version.mjs — do not edit manually.\n` +
	`export const VERSION = "${version}";\n`;

if (process.argv.includes("--check")) {
	const existing = readFileSync("src/version.ts", "utf8");
	if (existing !== content) {
		const match = existing.match(/VERSION = "([^"]+)"/);
		console.error(
			`src/version.ts is out of sync with package.json\n` +
				`  package.json : ${version}\n` +
				`  src/version.ts: ${match?.[1] ?? "(unreadable)"}`,
		);
		process.exit(1);
	}
	console.log(`src/version.ts is in sync with package.json (${version})`);
} else {
	writeFileSync("src/version.ts", content);
	console.log(`Generated src/version.ts with VERSION = "${version}"`);
}
