#!/usr/bin/env node
// Generates src/version.ts from package.json.
// With --check: exits non-zero if the file is out of sync.
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const version = pkg.version;
const serverVersion = pkg.supportedServerVersion;

if (!serverVersion) {
	console.error("package.json missing supportedServerVersion field");
	process.exit(1);
}

const content =
	`// Generated by scripts/gen-version.mjs — do not edit manually.\n` +
	`export const VERSION = "${version}";\n` +
	`export const SUPPORTED_SERVER_VERSION = "${serverVersion}";\n`;

if (process.argv.includes("--check")) {
	const existing = readFileSync("src/version.ts", "utf8");
	if (existing !== content) {
		const vMatch = existing.match(/VERSION = "([^"]+)"/);
		const sMatch = existing.match(/SUPPORTED_SERVER_VERSION = "([^"]+)"/);
		console.error(
			`src/version.ts is out of sync with package.json\n` +
				`  package.json version              : ${version}\n` +
				`  src/version.ts VERSION            : ${vMatch?.[1] ?? "(unreadable)"}\n` +
				`  package.json supportedServerVersion: ${serverVersion}\n` +
				`  src/version.ts SUPPORTED_SERVER_VERSION: ${sMatch?.[1] ?? "(unreadable)"}`,
		);
		process.exit(1);
	}
	console.log(
		`src/version.ts is in sync with package.json (${version}, server ${serverVersion})`,
	);
} else {
	writeFileSync("src/version.ts", content);
	console.log(
		`Generated src/version.ts with VERSION = "${version}", SUPPORTED_SERVER_VERSION = "${serverVersion}"`,
	);
}
